# Gazebo-ROS Bridge Configuration File
#
# This config file uses placeholders that are replaced at launch time in jackal_ekf_launch.py
#
# <robot_prefix> - Combined namespace/prefix from launch args (e.g., "jackal_") - matches URDF topics definitions
#
# Example: When prefix="jackal_":
#   Gazebo: /jackal_imu â†’ ROS2: /imu

- ros_topic_name: "/imu_0/data_raw"
  gz_topic_name: "/<robot_prefix>imu_0"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera_0/rgb/image"
  gz_topic_name : "/<robot_prefix>camera_0/image"
  ros_type_name : "sensor_msgs/msg/Image"
  gz_type_name  : "gz.msgs.Image"
  direction     : GZ_TO_ROS

- ros_topic_name: "/camera_0/points"
  gz_topic_name : "/<robot_prefix>camera_0/points"
  ros_type_name : "sensor_msgs/msg/PointCloud2"
  gz_type_name  : "gz.msgs.PointCloudPacked"
  direction     : GZ_TO_ROS

- ros_topic_name: "/camera_0/depth/image"
  gz_topic_name : "/<robot_prefix>camera_0/depth_image"
  ros_type_name : "sensor_msgs/msg/Image"
  gz_type_name  : "gz.msgs.Image"
  direction     : GZ_TO_ROS

- ros_topic_name: "/camera_0/rgb/camera_info"
  gz_topic_name : "/<robot_prefix>camera_0/camera_info"
  ros_type_name : "sensor_msgs/msg/CameraInfo"
  gz_type_name  : "gz.msgs.CameraInfo"
  direction     : GZ_TO_ROS

- ros_topic_name: "/scan"
  gz_topic_name: "/<robot_prefix>ouster"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/scan_cloud"
  gz_topic_name : "/<robot_prefix>ouster/points"
  ros_type_name : "sensor_msgs/msg/PointCloud2"
  gz_type_name  : "gz.msgs.PointCloudPacked"
  direction     : GZ_TO_ROS