<robot_prefix>ouster/os_driver:
  ros__parameters:
  # https://github.com/ouster-lidar/ouster-ros/blob/jazzy-devel/ouster-ros/config/driver_params.yaml
    sensor_hostname: '192.168.131.20'
    udp_dest: '192.168.131.1'
    mtp_dest: ''
    mtp_main: false
    lidar_mode: ''
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    ptp_utc_tai_offset: -37.0
    udp_profile_lidar: ''
    metadata: ''
    lidar_port: 7502
    imu_port: 7503
    sensor_frame: os_sensor
    lidar_frame: os_lidar
    imu_frame: os_imu
    point_cloud_frame: os_lidar
    pub_static_tf: false
    proc_mask: IMU|PCL|SCAN|IMG|RAW|TLM
    scan_ring: 0
    use_system_default_qos: false
    point_type: original
    azimuth_window_start: 0
    azimuth_window_end: 360000
    persist_config: false
    attempt_reconnect: false
    dormant_period_between_reconnects: 1.0
    max_failed_reconnect_attempts: 2147483647
    organized: true
    destagger: true
    min_range: 0.0
    max_range: 1000.0
    v_reduction: 1
    min_scan_valid_columns_ratio: 0.0
    mask_path: ''

# Attached to Jackal
<robot_prefix>camera_0/camera_0_node:
  ros__parameters:
  # https://github.com/realsenseai/realsense-ros/blob/ros2-master/realsense2_camera/launch/rs_launch.py
    camera_name: 'camera_0'
    device_type: 'd435'
    enable_color: true
    rgb_camera.color_profile: '1280x720x30' # 640x480x30
    enable_depth: true
    enable_infra: false
    enable_infra1: false
    enable_infra2: false
    depth_module.depth_profile: '1280x720x30'
    enable_rgbd: false
    pointcloud.enable: false
    enable_sync: true
    align_depth.enable: true
    publish_tf: true

# Attached to the arm (end-effector)
<robot_prefix>camera_1/camera_1_node:
  ros__parameters:
    camera_name: 'camera_1'
    device_type: 'd435'
    enable_color: true
    rgb_camera.color_profile: '640x480x30'
    enable_depth: true
    enable_infra: false
    enable_infra1: false
    enable_infra2: false
    depth_module.depth_profile: '640x480x30'
    enable_rgbd: false
    pointcloud.enable: false
    enable_sync: true
    align_depth.enable: true
    publish_tf: true