twist_mux:
  ros__parameters:
    use_stamped: True
    topics:
      joy:
        topic: 'joy_teleop/cmd_vel'
        timeout: 0.5
        priority: 10
      cli:
        topic: 'cmd_vel'
        timeout: 0.5
        priority: 1