teleop_twist_joy_node:
  ros__parameters:
    publish_stamped_twist: True
    axis_linear.x: 1
    axis_linear.y: 3
    axis_angular.yaw: 0
    enable_button: 4
    enable_turbo_button: 5
    scale_linear.x: 0.4
    scale_angular.yaw: 0.6
    scale_linear_turbo.x: 2.0
    scale_angular_turbo.yaw: 1.4

joy_linux_node:
  ros__parameters:
    dev: '/dev/input/js0' # pc
    # dev: '/dev/input/ps4' # jackal
    deadzone: 0.1
    autorepeat_rate: 20.0